### PR TITLE
Fix for missing assimp zip file when building dependancies.

### PR DESCRIPTION
**Pull request by pjohalloran**

### CODE REVIEW

**Comment by pjohalloran** [comment]
Hi,
Really cool project guys. I was getting started on this and had trouble building on Mac as i believe the URL for the assimp library has recently changed.  Fix is included.  Please let me know if ok.
Thanks,
PJ

**Comment by fodinabor** [comment]
Well I rather think it was a timeout as both links bring me to exactly the same page..

**Comment by pjohalloran** [comment]
Yeah in the browser it does but in xcode using curl it failed for me.

**Comment by pjohalloran** [comment]
Let me just repo it with original url and i will post the error i got :)

**Comment by pjohalloran** [comment]
Ok, my bad, must have been timeouts. Cant see that error now. Will close.

**Pull request closed without merging**
