### PR TITLE
Fix abs(double) not found on Linux.

### PR DESCRIPTION
**Pull request by fodinabor**

### CODE REVIEW

**Comment by fooflare** [comment]
+1 This PR is needed because the IDE can't be built on Linux

**Comment by marcopompili** [comment]
I was unable to build the IDE on Arch Linux:
TransformGizmo.cpp:550:94: error: call of overloaded ‘abs(Number)’ is ambiguous

The patch fixed the error.

**Comment by ochi12** [comment]
What patch? I am still unable to build the ide. I'm still getting the same error :p

**Comment by ochi12** [comment]
Oh, i understand, I'm supposed to change that file. Thanks, it worked

**Comment by KevinBalz** [comment]
+1

**Comment by ganthore** [comment]
+1

**Comment by chncdcksn** [comment]
+1

**Comment by J5lx** [comment]
+1

**Comment by skwerlman** [comment]
:+1:

**Pull request merged**
